2023-04-17 20:56:25.722 | WARNING  | cli_logger:<module>:102 - disabled
2023-04-17 20:56:25.730 | WARNING  | __main__:<module>:209 - No cliRequestsData found, use default where no CLI args are set
2023-04-17 20:56:25.731 | WARNING  | __main__:load_request_data:107 - cliRequestData.py could not be loaded. Using defaults with anonymous account
2023-04-17 20:56:27.647 | INFO     | __main__:generate:149 - {'finished': 0, 'processing': 1, 'restarted': 0, 'waiting': 0, 'done': False, 'faulted': False, 'wait_time': 15, 'queue_position': 0, 'kudos': 0.0, 'is_possible': True}
2023-04-17 20:56:29.390 | INFO     | __main__:generate:149 - {'finished': 0, 'processing': 1, 'restarted': 0, 'waiting': 0, 'done': False, 'faulted': False, 'wait_time': 13, 'queue_position': 0, 'kudos': 0.0, 'is_possible': True}
2023-04-17 20:56:31.068 | INFO     | __main__:generate:149 - {'finished': 0, 'processing': 1, 'restarted': 0, 'waiting': 0, 'done': False, 'faulted': False, 'wait_time': 11, 'queue_position': 0, 'kudos': 0.0, 'is_possible': True}
2023-04-17 20:56:33.010 | INFO     | __main__:generate:149 - {'finished': 0, 'processing': 1, 'restarted': 0, 'waiting': 0, 'done': False, 'faulted': False, 'wait_time': 9, 'queue_position': 0, 'kudos': 0.0, 'is_possible': True}
2023-04-17 20:56:34.473 | INFO     | __main__:generate:149 - {'finished': 0, 'processing': 1, 'restarted': 0, 'waiting': 0, 'done': False, 'faulted': False, 'wait_time': 8, 'queue_position': 0, 'kudos': 0.0, 'is_possible': True}
2023-04-17 20:56:35.841 | INFO     | __main__:generate:149 - {'finished': 0, 'processing': 1, 'restarted': 0, 'waiting': 0, 'done': False, 'faulted': False, 'wait_time': 7, 'queue_position': 0, 'kudos': 0.0, 'is_possible': True}
2023-04-17 20:56:37.506 | INFO     | __main__:generate:149 - {'finished': 0, 'processing': 1, 'restarted': 0, 'waiting': 0, 'done': False, 'faulted': False, 'wait_time': 5, 'queue_position': 0, 'kudos': 0.0, 'is_possible': True}
2023-04-17 20:56:39.319 | INFO     | __main__:generate:149 - {'finished': 0, 'processing': 1, 'restarted': 0, 'waiting': 0, 'done': False, 'faulted': False, 'wait_time': 3, 'queue_position': 0, 'kudos': 0.0, 'is_possible': True}
2023-04-17 20:56:40.793 | INFO     | __main__:generate:149 - {'finished': 0, 'processing': 1, 'restarted': 0, 'waiting': 0, 'done': False, 'faulted': False, 'wait_time': 2, 'queue_position': 0, 'kudos': 0.0, 'is_possible': True}
2023-04-17 20:56:42.494 | INFO     | __main__:generate:149 - {'finished': 1, 'processing': 0, 'restarted': 0, 'waiting': 0, 'done': True, 'faulted': False, 'wait_time': 0, 'queue_position': 0, 'kudos': 0.0, 'is_possible': True}
2023-04-17 20:56:45.376 | INFO     | __main__:generate:198 - Saved time/horde_generation.png
2023-04-17 21:10:12.324 | WARNING  | cli_logger:<module>:102 - disabled
2023-04-17 21:10:12.346 | WARNING  | __main__:<module>:209 - No cliRequestsData found, use default where no CLI args are set
2023-04-17 21:10:12.346 | WARNING  | __main__:load_request_data:107 - cliRequestData.py could not be loaded. Using defaults with anonymous account
2023-04-17 21:10:14.323 | INFO     | __main__:generate:149 - {'finished': 0, 'processing': 0, 'restarted': 0, 'waiting': 4, 'done': False, 'faulted': False, 'wait_time': 0, 'queue_position': 0, 'kudos': 0.0, 'is_possible': True}
2023-04-17 21:10:15.912 | INFO     | __main__:generate:149 - {'finished': 0, 'processing': 3, 'restarted': 0, 'waiting': 1, 'done': False, 'faulted': False, 'wait_time': 39, 'queue_position': 0, 'kudos': 0.0, 'is_possible': True}
2023-04-17 21:10:18.230 | INFO     | __main__:generate:149 - {'finished': 0, 'processing': 4, 'restarted': 0, 'waiting': 0, 'done': False, 'faulted': False, 'wait_time': 37, 'queue_position': 0, 'kudos': 0.0, 'is_possible': True}
2023-04-17 21:10:19.702 | INFO     | __main__:generate:149 - {'finished': 0, 'processing': 4, 'restarted': 0, 'waiting': 0, 'done': False, 'faulted': False, 'wait_time': 35, 'queue_position': 0, 'kudos': 0.0, 'is_possible': True}
2023-04-17 21:10:21.696 | INFO     | __main__:generate:149 - {'finished': 0, 'processing': 4, 'restarted': 0, 'waiting': 0, 'done': False, 'faulted': False, 'wait_time': 33, 'queue_position': 0, 'kudos': 0.0, 'is_possible': True}
2023-04-17 21:10:24.066 | INFO     | __main__:generate:149 - {'finished': 0, 'processing': 4, 'restarted': 0, 'waiting': 0, 'done': False, 'faulted': False, 'wait_time': 31, 'queue_position': 0, 'kudos': 0.0, 'is_possible': True}
2023-04-17 21:10:26.021 | INFO     | __main__:generate:149 - {'finished': 0, 'processing': 4, 'restarted': 0, 'waiting': 0, 'done': False, 'faulted': False, 'wait_time': 29, 'queue_position': 0, 'kudos': 0.0, 'is_possible': True}
2023-04-17 21:10:28.162 | INFO     | __main__:generate:149 - {'finished': 2, 'processing': 2, 'restarted': 0, 'waiting': 0, 'done': False, 'faulted': False, 'wait_time': 27, 'queue_position': 0, 'kudos': 0.0, 'is_possible': True}
2023-04-17 21:10:30.016 | INFO     | __main__:generate:149 - {'finished': 2, 'processing': 2, 'restarted': 0, 'waiting': 0, 'done': False, 'faulted': False, 'wait_time': 25, 'queue_position': 0, 'kudos': 28.0, 'is_possible': True}
2023-04-17 21:10:31.524 | INFO     | __main__:generate:149 - {'finished': 3, 'processing': 1, 'restarted': 0, 'waiting': 0, 'done': False, 'faulted': False, 'wait_time': 23, 'queue_position': 0, 'kudos': 42.0, 'is_possible': True}
2023-04-17 21:10:33.304 | INFO     | __main__:generate:149 - {'finished': 3, 'processing': 1, 'restarted': 0, 'waiting': 0, 'done': False, 'faulted': False, 'wait_time': 21, 'queue_position': 0, 'kudos': 42.0, 'is_possible': True}
2023-04-17 21:10:35.036 | INFO     | __main__:generate:149 - {'finished': 3, 'processing': 1, 'restarted': 0, 'waiting': 0, 'done': False, 'faulted': False, 'wait_time': 20, 'queue_position': 0, 'kudos': 42.0, 'is_possible': True}
2023-04-17 21:10:36.540 | INFO     | __main__:generate:149 - {'finished': 3, 'processing': 1, 'restarted': 0, 'waiting': 0, 'done': False, 'faulted': False, 'wait_time': 18, 'queue_position': 0, 'kudos': 42.0, 'is_possible': True}
2023-04-17 21:10:38.549 | INFO     | __main__:generate:149 - {'finished': 3, 'processing': 1, 'restarted': 0, 'waiting': 0, 'done': False, 'faulted': False, 'wait_time': 16, 'queue_position': 0, 'kudos': 42.0, 'is_possible': True}
2023-04-17 21:10:40.258 | INFO     | __main__:generate:149 - {'finished': 3, 'processing': 1, 'restarted': 0, 'waiting': 0, 'done': False, 'faulted': False, 'wait_time': 14, 'queue_position': 0, 'kudos': 42.0, 'is_possible': True}
2023-04-17 21:10:42.708 | INFO     | __main__:generate:149 - {'finished': 3, 'processing': 1, 'restarted': 0, 'waiting': 0, 'done': False, 'faulted': False, 'wait_time': 12, 'queue_position': 0, 'kudos': 42.0, 'is_possible': True}
2023-04-17 21:10:44.269 | INFO     | __main__:generate:149 - {'finished': 3, 'processing': 1, 'restarted': 0, 'waiting': 0, 'done': False, 'faulted': False, 'wait_time': 10, 'queue_position': 0, 'kudos': 42.0, 'is_possible': True}
2023-04-17 21:10:45.967 | INFO     | __main__:generate:149 - {'finished': 3, 'processing': 1, 'restarted': 0, 'waiting': 0, 'done': False, 'faulted': False, 'wait_time': 9, 'queue_position': 0, 'kudos': 42.0, 'is_possible': True}
2023-04-17 21:10:48.133 | INFO     | __main__:generate:149 - {'finished': 4, 'processing': 0, 'restarted': 0, 'waiting': 0, 'done': True, 'faulted': False, 'wait_time': 0, 'queue_position': 0, 'kudos': 42.0, 'is_possible': True}
2023-04-17 21:10:50.497 | ERROR    | __main__:<module>:226 - An error has been caught in function '<module>', process 'MainProcess' (27618), thread 'MainThread' (140684320947072):
Traceback (most recent call last):

> File "/home/mak448a/Documents/Programming/Python/Stable-Diffusion-Bot/AI-Horde/cli_request.py", line 226, in <module>
    generate()
    └ <function generate at 0x7ff38f511760>

  File "/home/mak448a/Documents/Programming/Python/Stable-Diffusion-Bot/AI-Horde/cli_request.py", line 187, in generate
    with open(final_filename, 'wb') as handler:
              └ '0_1681783812.1799085/horde_generation.png'

FileNotFoundError: [Errno 2] No such file or directory: '0_1681783812.1799085/horde_generation.png'
2023-04-17 21:12:59.868 | WARNING  | cli_logger:<module>:102 - disabled
2023-04-17 21:12:59.877 | WARNING  | __main__:<module>:209 - No cliRequestsData found, use default where no CLI args are set
2023-04-17 21:12:59.877 | WARNING  | __main__:load_request_data:107 - cliRequestData.py could not be loaded. Using defaults with anonymous account
2023-04-17 21:13:01.604 | INFO     | __main__:generate:149 - {'finished': 0, 'processing': 0, 'restarted': 0, 'waiting': 2, 'done': False, 'faulted': False, 'wait_time': 0, 'queue_position': 0, 'kudos': 0.0, 'is_possible': True}
2023-04-17 21:13:03.791 | INFO     | __main__:generate:149 - {'finished': 0, 'processing': 0, 'restarted': 0, 'waiting': 2, 'done': False, 'faulted': False, 'wait_time': 579, 'queue_position': 458, 'kudos': 0.0, 'is_possible': True}
2023-04-17 21:13:05.791 | INFO     | __main__:generate:149 - {'finished': 0, 'processing': 0, 'restarted': 0, 'waiting': 2, 'done': False, 'faulted': False, 'wait_time': 581, 'queue_position': 462, 'kudos': 0.0, 'is_possible': True}
2023-04-17 21:13:07.499 | INFO     | __main__:generate:149 - {'finished': 0, 'processing': 1, 'restarted': 0, 'waiting': 1, 'done': False, 'faulted': False, 'wait_time': 592, 'queue_position': 458, 'kudos': 0.0, 'is_possible': True}
2023-04-17 21:13:09.422 | INFO     | __main__:generate:149 - {'finished': 0, 'processing': 1, 'restarted': 0, 'waiting': 1, 'done': False, 'faulted': False, 'wait_time': 585, 'queue_position': 447, 'kudos': 0.0, 'is_possible': True}
2023-04-17 21:13:11.142 | INFO     | __main__:generate:149 - {'finished': 0, 'processing': 1, 'restarted': 0, 'waiting': 1, 'done': False, 'faulted': False, 'wait_time': 583, 'queue_position': 447, 'kudos': 0.0, 'is_possible': True}
2023-04-17 21:13:13.617 | INFO     | __main__:generate:149 - {'finished': 0, 'processing': 2, 'restarted': 0, 'waiting': 0, 'done': False, 'faulted': False, 'wait_time': 14, 'queue_position': 0, 'kudos': 0.0, 'is_possible': True}
2023-04-17 21:13:15.386 | INFO     | __main__:generate:149 - {'finished': 0, 'processing': 2, 'restarted': 0, 'waiting': 0, 'done': False, 'faulted': False, 'wait_time': 13, 'queue_position': 0, 'kudos': 0.0, 'is_possible': True}
2023-04-17 21:13:17.642 | INFO     | __main__:generate:149 - {'finished': 0, 'processing': 2, 'restarted': 0, 'waiting': 0, 'done': False, 'faulted': False, 'wait_time': 10, 'queue_position': 0, 'kudos': 0.0, 'is_possible': True}
2023-04-17 21:13:19.653 | INFO     | __main__:generate:149 - {'finished': 0, 'processing': 2, 'restarted': 0, 'waiting': 0, 'done': False, 'faulted': False, 'wait_time': 8, 'queue_position': 0, 'kudos': 0.0, 'is_possible': True}
2023-04-17 21:13:21.493 | INFO     | __main__:generate:149 - {'finished': 0, 'processing': 2, 'restarted': 0, 'waiting': 0, 'done': False, 'faulted': False, 'wait_time': 6, 'queue_position': 0, 'kudos': 0.0, 'is_possible': True}
2023-04-17 21:13:23.110 | INFO     | __main__:generate:149 - {'finished': 0, 'processing': 2, 'restarted': 0, 'waiting': 0, 'done': False, 'faulted': False, 'wait_time': 5, 'queue_position': 0, 'kudos': 0.0, 'is_possible': True}
2023-04-17 21:13:25.292 | INFO     | __main__:generate:149 - {'finished': 1, 'processing': 1, 'restarted': 0, 'waiting': 0, 'done': False, 'faulted': False, 'wait_time': 3, 'queue_position': 0, 'kudos': 14.0, 'is_possible': True}
2023-04-17 21:13:27.426 | INFO     | __main__:generate:149 - {'finished': 1, 'processing': 1, 'restarted': 0, 'waiting': 0, 'done': False, 'faulted': False, 'wait_time': 1, 'queue_position': 0, 'kudos': 14.0, 'is_possible': True}
2023-04-17 21:13:29.771 | INFO     | __main__:generate:149 - {'finished': 1, 'processing': 1, 'restarted': 0, 'waiting': 0, 'done': False, 'faulted': False, 'wait_time': 0, 'queue_position': 0, 'kudos': 14.0, 'is_possible': True}
2023-04-17 21:13:31.484 | INFO     | __main__:generate:149 - {'finished': 2, 'processing': 0, 'restarted': 0, 'waiting': 0, 'done': True, 'faulted': False, 'wait_time': 0, 'queue_position': 0, 'kudos': 28.0, 'is_possible': True}
2023-04-17 21:13:33.959 | ERROR    | __main__:<module>:226 - An error has been caught in function '<module>', process 'MainProcess' (28273), thread 'MainThread' (139797012306816):
Traceback (most recent call last):

> File "/home/mak448a/Documents/Programming/Python/Stable-Diffusion-Bot/AI-Horde/cli_request.py", line 226, in <module>
    generate()
    └ <function generate at 0x7f24f76d9800>

  File "/home/mak448a/Documents/Programming/Python/Stable-Diffusion-Bot/AI-Horde/cli_request.py", line 187, in generate
    with open(final_filename, 'wb') as handler:
              └ '0_time/horde_generation.png'

FileNotFoundError: [Errno 2] No such file or directory: '0_time/horde_generation.png'
2023-04-17 21:13:56.009 | WARNING  | cli_logger:<module>:102 - disabled
2023-04-17 21:13:56.020 | WARNING  | __main__:<module>:209 - No cliRequestsData found, use default where no CLI args are set
2023-04-17 21:13:56.020 | WARNING  | __main__:load_request_data:107 - cliRequestData.py could not be loaded. Using defaults with anonymous account
2023-04-17 21:13:59.150 | INFO     | __main__:generate:149 - {'finished': 0, 'processing': 0, 'restarted': 0, 'waiting': 2, 'done': False, 'faulted': False, 'wait_time': 0, 'queue_position': 0, 'kudos': 0.0, 'is_possible': True}
2023-04-17 21:14:01.197 | INFO     | __main__:generate:149 - {'finished': 0, 'processing': 0, 'restarted': 0, 'waiting': 2, 'done': False, 'faulted': False, 'wait_time': 545, 'queue_position': 432, 'kudos': 0.0, 'is_possible': True}
2023-04-17 21:14:02.450 | INFO     | __main__:generate:160 - Cancelling 8a320fd4-8d44-48fa-b249-466804c9a2a9...
2023-04-17 21:14:17.984 | WARNING  | cli_logger:<module>:102 - disabled
2023-04-17 21:14:17.993 | WARNING  | __main__:<module>:209 - No cliRequestsData found, use default where no CLI args are set
2023-04-17 21:14:17.993 | WARNING  | __main__:load_request_data:107 - cliRequestData.py could not be loaded. Using defaults with anonymous account
2023-04-17 21:14:20.419 | INFO     | __main__:generate:149 - {'finished': 0, 'processing': 0, 'restarted': 0, 'waiting': 2, 'done': False, 'faulted': False, 'wait_time': 0, 'queue_position': 0, 'kudos': 0.0, 'is_possible': True}
2023-04-17 21:14:22.765 | INFO     | __main__:generate:149 - {'finished': 0, 'processing': 0, 'restarted': 0, 'waiting': 2, 'done': False, 'faulted': False, 'wait_time': 525, 'queue_position': 419, 'kudos': 0.0, 'is_possible': True}
2023-04-17 21:14:24.232 | INFO     | __main__:generate:149 - {'finished': 0, 'processing': 2, 'restarted': 0, 'waiting': 0, 'done': False, 'faulted': False, 'wait_time': 16, 'queue_position': 0, 'kudos': 0.0, 'is_possible': True}
2023-04-17 21:14:25.666 | INFO     | __main__:generate:149 - {'finished': 0, 'processing': 2, 'restarted': 0, 'waiting': 0, 'done': False, 'faulted': False, 'wait_time': 14, 'queue_position': 0, 'kudos': 0.0, 'is_possible': True}
2023-04-17 21:14:27.621 | INFO     | __main__:generate:149 - {'finished': 0, 'processing': 2, 'restarted': 0, 'waiting': 0, 'done': False, 'faulted': False, 'wait_time': 13, 'queue_position': 0, 'kudos': 0.0, 'is_possible': True}
2023-04-17 21:14:30.052 | INFO     | __main__:generate:149 - {'finished': 0, 'processing': 2, 'restarted': 0, 'waiting': 0, 'done': False, 'faulted': False, 'wait_time': 10, 'queue_position': 0, 'kudos': 0.0, 'is_possible': True}
2023-04-17 21:14:32.278 | INFO     | __main__:generate:149 - {'finished': 0, 'processing': 2, 'restarted': 0, 'waiting': 0, 'done': False, 'faulted': False, 'wait_time': 8, 'queue_position': 0, 'kudos': 0.0, 'is_possible': True}
2023-04-17 21:14:33.780 | INFO     | __main__:generate:149 - {'finished': 1, 'processing': 1, 'restarted': 0, 'waiting': 0, 'done': False, 'faulted': False, 'wait_time': 3, 'queue_position': 0, 'kudos': 0.0, 'is_possible': True}
2023-04-17 21:14:35.695 | INFO     | __main__:generate:149 - {'finished': 2, 'processing': 0, 'restarted': 0, 'waiting': 0, 'done': True, 'faulted': False, 'wait_time': 0, 'queue_position': 0, 'kudos': 14.0, 'is_possible': True}
2023-04-17 21:14:37.947 | ERROR    | __main__:<module>:226 - An error has been caught in function '<module>', process 'MainProcess' (28540), thread 'MainThread' (139736872491904):
Traceback (most recent call last):

> File "/home/mak448a/Documents/Programming/Python/Stable-Diffusion-Bot/AI-Horde/cli_request.py", line 226, in <module>
    generate()
    └ <function generate at 0x7f16f6d19800>

  File "/home/mak448a/Documents/Programming/Python/Stable-Diffusion-Bot/AI-Horde/cli_request.py", line 187, in generate
    with open(final_filename, 'wb') as handler:
              └ '0_time/horde_generation.png'

FileNotFoundError: [Errno 2] No such file or directory: '0_time/horde_generation.png'
2023-04-17 21:15:46.061 | WARNING  | cli_logger:<module>:102 - disabled
2023-04-17 21:15:46.071 | WARNING  | __main__:<module>:209 - No cliRequestsData found, use default where no CLI args are set
2023-04-17 21:15:46.071 | WARNING  | __main__:load_request_data:107 - cliRequestData.py could not be loaded. Using defaults with anonymous account
2023-04-17 21:15:49.249 | INFO     | __main__:generate:149 - {'finished': 0, 'processing': 0, 'restarted': 0, 'waiting': 2, 'done': False, 'faulted': False, 'wait_time': 0, 'queue_position': 0, 'kudos': 0.0, 'is_possible': True}
2023-04-17 21:15:51.114 | INFO     | __main__:generate:149 - {'finished': 0, 'processing': 2, 'restarted': 0, 'waiting': 0, 'done': False, 'faulted': False, 'wait_time': 16, 'queue_position': 0, 'kudos': 0.0, 'is_possible': True}
2023-04-17 21:15:52.886 | INFO     | __main__:generate:149 - {'finished': 0, 'processing': 2, 'restarted': 0, 'waiting': 0, 'done': False, 'faulted': False, 'wait_time': 14, 'queue_position': 0, 'kudos': 0.0, 'is_possible': True}
2023-04-17 21:15:54.430 | INFO     | __main__:generate:149 - {'finished': 0, 'processing': 2, 'restarted': 0, 'waiting': 0, 'done': False, 'faulted': False, 'wait_time': 13, 'queue_position': 0, 'kudos': 0.0, 'is_possible': True}
2023-04-17 21:15:55.851 | INFO     | __main__:generate:149 - {'finished': 0, 'processing': 2, 'restarted': 0, 'waiting': 0, 'done': False, 'faulted': False, 'wait_time': 11, 'queue_position': 0, 'kudos': 0.0, 'is_possible': True}
2023-04-17 21:15:58.217 | INFO     | __main__:generate:149 - {'finished': 0, 'processing': 2, 'restarted': 0, 'waiting': 0, 'done': False, 'faulted': False, 'wait_time': 9, 'queue_position': 0, 'kudos': 0.0, 'is_possible': True}
2023-04-17 21:15:59.630 | INFO     | __main__:generate:149 - {'finished': 0, 'processing': 2, 'restarted': 0, 'waiting': 0, 'done': False, 'faulted': False, 'wait_time': 8, 'queue_position': 0, 'kudos': 0.0, 'is_possible': True}
2023-04-17 21:16:01.453 | INFO     | __main__:generate:149 - {'finished': 0, 'processing': 2, 'restarted': 0, 'waiting': 0, 'done': False, 'faulted': False, 'wait_time': 6, 'queue_position': 0, 'kudos': 0.0, 'is_possible': True}
2023-04-17 21:16:02.962 | INFO     | __main__:generate:149 - {'finished': 1, 'processing': 1, 'restarted': 0, 'waiting': 0, 'done': False, 'faulted': False, 'wait_time': 5, 'queue_position': 0, 'kudos': 14.0, 'is_possible': True}
2023-04-17 21:16:05.275 | INFO     | __main__:generate:149 - {'finished': 1, 'processing': 1, 'restarted': 0, 'waiting': 0, 'done': False, 'faulted': False, 'wait_time': 2, 'queue_position': 0, 'kudos': 14.0, 'is_possible': True}
2023-04-17 21:16:06.757 | INFO     | __main__:generate:149 - {'finished': 1, 'processing': 1, 'restarted': 0, 'waiting': 0, 'done': False, 'faulted': False, 'wait_time': 1, 'queue_position': 0, 'kudos': 14.0, 'is_possible': True}
2023-04-17 21:16:08.460 | INFO     | __main__:generate:149 - {'finished': 2, 'processing': 0, 'restarted': 0, 'waiting': 0, 'done': True, 'faulted': False, 'wait_time': 0, 'queue_position': 0, 'kudos': 28.0, 'is_possible': True}
2023-04-17 21:16:10.762 | ERROR    | __main__:<module>:226 - An error has been caught in function '<module>', process 'MainProcess' (28819), thread 'MainThread' (140466886249344):
Traceback (most recent call last):

> File "/home/mak448a/Documents/Programming/Python/Stable-Diffusion-Bot/AI-Horde/cli_request.py", line 226, in <module>
    generate()
    └ <function generate at 0x7fc0ef109800>

  File "/home/mak448a/Documents/Programming/Python/Stable-Diffusion-Bot/AI-Horde/cli_request.py", line 187, in generate
    with open(final_filename, 'wb') as handler:
              └ '0_time/'

IsADirectoryError: [Errno 21] Is a directory: '0_time/'
